blog/urls.py
from django.conf.urls import url
from django.contrib import admin

from blog import views

app_name = 'blog'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'momos/$', views.momos, name='momos'),
    url(r'momos/new$', views.new_momo, name='new_momo'),
]

momazos/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

app_name = 'momazos'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'momos/$', views.momos, name='momos'),
]

momos/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^momo-admin/', admin.site.urls),
    url(r'^', include('blog.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


class Momo(models.Model):
    name = models.CharField(max_length=80, default='')
    description = models.CharField(max_length=150, default='')
    image = models.ImageField(blank=False, upload_to='media/momos', default='')

blog/forms.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals
from django import forms

from blog.models import Momo


class MomoForm(forms.ModelForm):
    class Meta:
        model = Momo
        fields = '__all__'

blog/views.py
from django.shortcuts import render, redirect

from blog.forms import MomoForm
from blog.models import Momo


def index(request):
    template = 'index.html'
    context = {
        'pregunta': 'kiere magia prro?',
        'magia': 'toma tus momos :V'
    }

    return render(request, template, context)


def momos(request):
    los_momos = Momo.objects.all()
    template = 'momos/momos.html'
    context = {
        'momos': los_momos,
    }

    return render(request, template, context)


def new_momo(request):
    if request.method == 'POST':
        form = MomoForm(request.POST, request.FILES)
        if form.is_valid():
            momo = form.save(commit=False)
            momo.save()
            return redirect('/momos/')
    else:
        form = MomoForm()

    momo_objects = Momo.objects.all()
    template = 'momos/new_momo.html'
    context = {
        'momos': momo_objects,
        'form': form
    }

    return render(request, template, context)

momazos/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Momo

def index(request):
    template = 'index.html'
    context = {
        'pregunta': 'kiere magia prro?',
        'magia': 'toma tus momos :V'
    }

    return render(request, template, context)


def momos(request):
    los_momos = Momo.objects.all()
    template = 'momos.html'
    context = {
        'momos': los_momos,
    }

    return render(request, template, context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>MOMAZOS</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">

  <!-- google fonts -->
  <link href="https://fonts.googleapis.com/css?family=Lobster|Open+Sans" rel="stylesheet"> 

  <!-- icon fonts google-->
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
  rel="stylesheet">

  <!-- styles -->
  <link rel="stylesheet" href="{% static "css/styles.css" %}">
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-dark bg-inverse" id="navbar">
    <a class="navbar-brand nav-title" href="{% url 'blog:index' %}">Momero</a>
    <ul class="nav navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:momos' %}">Momos <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:new_momo' %}">Momea <span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </nav>
  {% block content %}

  {% endblock %}
</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
</html>

templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	<h1>Bienvenido a momolandia</h1>
</div>

{% endblock %}

templates/momos/momos.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container-fluid">
	<h1>Galeria de Momos :v </h1>

	<div class="row">
		{% for momo in momos %}
		<div class="col-xs-12 col-md-6 col-lg-4 col-xl-3">
			<div class="card">
				<img class="card-img-top img-momo" src="{{ momo.image.url }}" alt="Card image cap">
				<div class="card-block">
					<h4 class="card-title">{{ momo.name }}</h4>
					<p class="card-text">{{ momo.description }}</p>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</div>
{% endblock %}

templates/momos/new_momo.html
{% extends "base.html" %}

{% block content %}
<div class="container">
	<h1>Sube tu propio momo :v</h1>
	<form method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-success" type="submit">
		Subir momo <i class="material-icons">toys</i>
		</button>
	</form>
</div>
{% endblock content %}